server:
  port: 50001
spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:50000"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:50001/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    #Self-Preservation ??? ?? ? ? ?? ????. ????? ?? ????? ?? ?? ?? ????.
    enable-self-preservation: true
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busresfresh
